# https://github.com/CocoaPods/Rome#installation

platform :ios, '14.0'

use_frameworks!

plugin 'cocoapods-rome', { :pre_compile => Proc.new { |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end

    installer.pods_project.save
},

    dsym: false,
    configuration: 'Release'
}

target 'stripeqs' do
    pod 'Stripe', '23.27.4'
    pod 'StripeCardScan', '23.27.4'
    pod 'StripePaymentSheet', '23.27.4'
    pod 'StripeFinancialConnections', '23.27.4'
    pod 'StripeIdentity', '23.27.4'
end