name: Android Binding Libraries - NordicSemi DFU
run-name: ${{ inputs.LIB_ARTIFACT }} 🚀 NuGet

on:
  workflow_dispatch:
    inputs:
      LIB_ARTIFACT:
        description: 'Android library to publish'
        required: true
        type: choice
        options:
        - no.nordicsemi.android:dfu:2.4.2
        - no.nordicsemi.android:dfu:2.5.0
        - no.nordicsemi.android:dfu:2.6.0
        - no.nordicsemi.android:dfu:2.7.0        
        - no.nordicsemi.android:dfu:2.8.0
        - no.nordicsemi.android:dfu:2.9.0

jobs:
  build-then-publish:
    uses: ./.github/workflows/reusable-android-build.yml
    with:
      artifact: ${{ inputs.LIB_ARTIFACT }}
      dotnet-version: '9.0'
      java-version: '21'
      requires-mapbox-token: false
      requires-drivesmart-credentials: false
    secrets:
      NUGET_PUSH_API_KEY: ${{ secrets.NUGET_PUSH_API_KEY }}
