name: Android Binding Libraries - Filament
run-name: ${{ inputs.LIB_ARTIFACT }} 🚀 NuGet

on:
  workflow_dispatch:
    inputs:
      LIB_ARTIFACT:
        description: 'Android library to publish'
        required: true
        type: choice
        options:   
        - com.google.android.filament:filament-utils-android:1.56.0

jobs:
  build-then-publish:
    uses: ./.github/workflows/reusable-android-build.yml
    with:
      artifact: ${{ inputs.LIB_ARTIFACT }}
      dotnet-version: '9.0'
      java-version: '21'
      requires-mapbox-token: false
      requires-drivesmart-credentials: false
    secrets:
      NUGET_PUSH_API_KEY: ${{ secrets.NUGET_PUSH_API_KEY }}