name: Android Binding Libraries - Ktor
run-name: ${{ inputs.LIB_ARTIFACT }} 🚀 NuGet

on:
  workflow_dispatch:
    inputs:
      LIB_ARTIFACT:
        description: 'Android library to publish'
        required: true
        type: choice
        options: 
        - io.ktor:ktor-io-jvm:2.3.8    
        - io.ktor:ktor-client-darwin:2.3.8  
        - io.ktor:ktor-client-okhttp:2.3.11
        - io.ktor:ktor-client-serialization:2.3.11
        - io.ktor:ktor-serialization-kotlinx-json:2.3.11
        - io.ktor:ktor-client-content-negotiation:2.3.11
        - io.ktor:ktor-websocket-serialization:2.3.11
        - io.ktor:ktor-websockets:2.3.11

jobs:
  build-then-publish:
    uses: ./.github/workflows/reusable-android-build.yml
    with:
      artifact: ${{ inputs.LIB_ARTIFACT }}
      dotnet-version: '9.0'
      java-version: '21'
      requires-mapbox-token: false
      requires-drivesmart-credentials: false
    secrets:
      NUGET_PUSH_API_KEY: ${{ secrets.NUGET_PUSH_API_KEY }}