name: Android Binding Libraries - Stripe
run-name: ${{ inputs.LIB_ARTIFACT }} 🚀 NuGet

on:
  workflow_dispatch:
    inputs:
      LIB_ARTIFACT:
        description: 'Android library to publish'
        required: true
        type: choice
        options:   
        - com.stripe:hcaptcha:21.3.1 
        - com.stripe:stripe-core:21.3.1
        - com.stripe:stripe-ui-core:21.3.1
        - com.stripe:payments-model:21.3.1
        - com.stripe:stripe-3ds2-android:6.2.0
        - com.stripe:payments-core:21.3.1
        - com.stripe:payments-ui-core:21.3.1
        - com.stripe:link:20.48.3
        - com.stripe:paymentsheet:21.3.1
        - com.stripe:stripe-android:21.3.1
        - com.stripe:stripeterminal-external:4.1.0   
        - com.stripe:stripeterminal-internal-common:4.1.0
        - com.stripe:stripeterminal-core:4.1.0
        - com.stripe:stripeterminal:4.1.0

jobs:
  build-then-publish:
    uses: ./.github/workflows/reusable-android-build.yml
    with:
      artifact: ${{ inputs.LIB_ARTIFACT }}
      dotnet-version: '9.0'
      java-version: '21'
      requires-mapbox-token: false
      requires-drivesmart-credentials: false
    secrets:
      NUGET_PUSH_API_KEY: ${{ secrets.NUGET_PUSH_API_KEY }}
